### ISSUE TITLE
[optparse] Conflicting Option String

### ISSUE THREAD

**Issue by naphthalene** [makaimc/underwear#7]
My Environment:

Python 2.7.10
Ubuntu 15.10
pip 8.1.0

Installed underwear via `pip install underwear`

Traceback:

```
$ python manage.py deploy
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "<scrubbed>/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "<scrubbed>/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "<scrubbed>/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "<scrubbed>/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "<scrubbed>/local/lib/python2.7/site-packages/underwear/management/commands/deploy.py", line 14, in handle
    '--extra-vars', '@%s' % './deploy/underwear.yml'])
  File "<scrubbed>/local/lib/python2.7/site-packages/underwear/run_underwear.py", line 55, in deploy
    help="set additional variables as key=value or YAML/JSON", default=[])
  File "/usr/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/usr/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option -e/--extra-vars: conflicting option string(s): -e, --extra-vars
```

New deptree:

```
underwear==0.4.5
  - ansible [installed: 1.9.4]
    - paramiko [installed: 1.16.0]
      - ecdsa [required: >=0.11, installed: 0.13]
      - pycrypto [required: >=2.1, installed: 2.6.1]
    - setuptools
    - PyYAML [installed: 3.11]
    - pycrypto [required: >=2.6, installed: 2.6.1]
    - jinja2 [installed: 2.8]
      - MarkupSafe [installed: 0.23]
```

Error can be resolved by removing [this line](https://github.com/makaimc/underwear/blob/master/underwear/run_underwear.py#L54)

**Comment by naphthalene** [comment]
All issues resolved by manually installing `ansible==1.8.4`

**Comment by JJ** [comment]
:+1:
